name: tindart
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+4

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^5.6.6
  firebase_auth: ^5.5.3
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.0.2
  go_router: ^15.1.1
  google_sign_in: ^6.3.0
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_icon.png
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/icons.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/android_icon.png"
  image_path_ios: "assets/icons/ios_icon.png"  
  min_sdk_android: 21  # Optional: Set min SDK for adaptive icons
