name: tindart
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+4

environment:
  sdk: ^3.7.2

dependencies:
  cloud_firestore: ^5.6.6
  firebase_core: ^3.13.0
  firebase_storage: ^12.4.5
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
