name: tindart
description: "Swipe to find art you love."
publish_to: "none"
version: 0.2.17+27

environment:
  sdk: ">=3.3.0 <4.0.0"
  flutter: 3.38.3

dependencies:
  wallpaper_manager_plus: ^2.0.1
  gal: ^2.3.0
  cloud_firestore: ^6.1.0
  cloud_functions: ^6.0.4
  firebase_analytics: ^12.0.4
  firebase_auth: ^6.1.2
  firebase_core: ^4.2.1
  firebase_crashlytics: ^5.0.5
  firebase_storage: ^13.0.4
  flutter:
    sdk: flutter
  flutter_card_swiper: ^7.0.2
  go_router: ^17.0.1
  google_sign_in: ^6.2.1
  http: ^1.4.0
  path_provider: ^2.1.5
  rxdart: ^0.28.0
  shared_preferences: ^2.5.3
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3
  fake_cloud_firestore: ^4.0.0
  firebase_auth_mocks: ^0.15.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/google_icon.png
  fonts:
    - family: CustomIcons
      fonts:
        - asset: assets/fonts/icons.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path_android: "assets/icons/android_icon.png"
  image_path_ios: "assets/icons/ios_icon.png"
  min_sdk_android: 21 # Optional: Set min SDK for adaptive icons
  # Run: flutter pub run flutter_launcher_icons:main
