name: read_firestore
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

dependencies:
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  csv: ^6.0.0
  http: ^1.4.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.0
