name: read_firestore
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.8.0

dependencies:
  googleapis: ^11.0.0
  googleapis_auth: ^1.3.0
  csv: ^5.0.1
  args: ^2.4.0
  http: ^0.13.6

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
